# Full Configuration File for sx
# With every official option and default values


# ================= sx =================

# Option to change the Default Start Message to for example
# Set to true for this!
--overwrite-start-message=false

# Enter here the File name! Path starts in the Home Directory
--start-message-file=empty.txt

# View my dotfiles for Examples!

# Change the Default Terminal Shell which is used on Windows
--windows-default-shell=cmd

# Change the Default Terminal Shell which is used on Linux
--linux-default-shell=bash

# Print the Version and the Buildtime after the Custom Start Message
# true, or false - Default is false
--add-info-to-start-message=true


# ================= Multi =================

# Min and Max Number for the Game, Default is 1 and 1000
--numberguess-min=1
--numberguess-max=1000


# ================= Windows UI =================

# Button Callbacks for the Windows UI
--windows-sx-ui-button1=hi
--windows-sx-ui-button2=hi
--windows-sx-ui-button3=hi
--windows-sx-ui-button4=hi
--windows-sx-ui-button5=hi
--windows-sx-ui-button6=hi
--windows-sx-ui-button7=hi
--windows-sx-ui-button8=hi
--windows-sx-ui-button9=hi
--windows-sx-ui-button10=hi
--windows-sx-ui-button11=hi
--windows-sx-ui-button12=hi
--windows-sx-ui-button13=hi
--windows-sx-ui-button14=hi
--windows-sx-ui-button15=hi
--windows-sx-ui-button16=hi

# Buttom names for the Windows UI
# Use echo so that the Name will be retuned as Output and not
# as Command to call when the Button is Clicked
--windows-sx-ui-button1-name=echo Hallo World
--windows-sx-ui-button2-name=echo Hallo World
--windows-sx-ui-button3-name=echo Hallo World
--windows-sx-ui-button4-name=echo Hallo World
--windows-sx-ui-button5-name=echo Hallo World
--windows-sx-ui-button6-name=echo Hallo World
--windows-sx-ui-button7-name=echo Hallo World
--windows-sx-ui-button8-name=echo Hallo World
--windows-sx-ui-button9-name=echo Hallo World
--windows-sx-ui-button10-name=echo Hallo World
--windows-sx-ui-button11-name=echo Hallo World
--windows-sx-ui-button12-name=echo Hallo World
--windows-sx-ui-button13-name=echo Hallo World
--windows-sx-ui-button14-name=echo Hallo World
--windows-sx-ui-button15-name=echo Hallo World
--windows-sx-ui-button16-name=echo Hallo World
